# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date published')),
                ('campaign_description', models.TextField()),
                ('amount_crowdfunded', models.DecimalField(decimal_places=2, max_digits=5)),
                ('campaign_image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
