# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0002_campaign_num_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_image_url',
            field=models.TextField(default='https://commons.wikimedia.org/wiki/File:Pup2.JPG'),
            preserve_default=False,
        ),
    ]
