# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0004_auto_20160315_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='stat_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_1_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_2_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='stat_3_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
