# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0024_auto_20160412_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='crowdcop_web.Campaign', verbose_name='Below is a list of our existing campaigns. If any of these campaigns are relevant to your tip, please select it.'),
        ),
    ]
