# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0026_auto_20160412_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalid',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='How can we contact you?'),
        ),
        migrations.AlterField(
            model_name='paypalid',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Your Name (not required):'),
        ),
        migrations.AlterField(
            model_name='paypalid',
            name='paypal_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='If you wish to be compensated for your tip, please enter your Paypal username here (Not Required):'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='suspect_features',
            field=models.TextField(blank=True, verbose_name='Scars, Marks, Tattoos, Piercings'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='suspect_other',
            field=models.TextField(blank=True, verbose_name='Other suspect details (clothing, telephone, employment, etc.)'),
        ),
    ]
