# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0030_auto_20160413_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdcopuser',
            name='following',
            field=models.ManyToManyField(to='crowdcop_web.Campaign'),
        ),
    ]
