# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0033_auto_20160525_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
