# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0003_campaign_campaign_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_image_url',
            field=models.URLField(),
        ),
    ]
