# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0005_auto_20160316_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='stat_1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='stat_2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='stat_3',
            field=models.CharField(max_length=25),
        ),
    ]
