# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0011_auto_20160412_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='crowdcop_web.Campaign'),
            preserve_default=False,
        ),
    ]
