# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0014_auto_20160412_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='suspect_eye_color',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('AMBER', 'Amber'), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('GREEN', 'Green'), ('HAZEL', 'Hazel'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
