# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0019_auto_20160412_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='details',
            field=models.TextField(verbose_name='>What happened? (Be specific about the alleged crime and any victims).'),
        ),
    ]
