# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0021_auto_20160412_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateTimeField(verbose_name='When did this occur (If known, enter date and time).'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='location',
            field=models.TextField(verbose_name='Where did this occur? (Please be as specific as possible about the location. Include house number, street, color of house, etc.).'),
        ),
    ]
