# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0022_auto_20160412_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='suspect_features',
            field=models.TextField(verbose_name='Scars, Marks, Tattoos, Piercings'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='suspect_other',
            field=models.TextField(verbose_name='Other suspect details (clothing, telephone, employment, etc.)'),
        ),
    ]
