# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0031_crowdcopuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdcopuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
