# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0032_auto_20160502_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 25, 18, 27, 28, 556090, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='tx',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
