# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0035_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='CampaignView',
        ),
    ]
