# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0036_auto_20160604_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
