# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0037_auto_20160609_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdcopuser',
            name='profile_picture',
            field=models.ImageField(default='https://scontent-lga3-1.xx.fbcdn.net/hprofile-xap1/v/t1.0-1/p320x320/12341036_1501783263450006_2048940113394308522_n.jpg?oh=8fe5a3c7a8a16776a753d0426a4ee939&oe=5767B15F', upload_to=b''),
            preserve_default=False,
        ),
    ]
