# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='num_tips',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
