# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0008_paypalid_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='tip',
        ),
        migrations.AddField(
            model_name='paypalid',
            name='contact_info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paypalid',
            name='contact_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='campaign',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='related_campaign', to='crowdcop_web.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='suspect_eye_color',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='suspect_features',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='suspect_gender',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='suspect_hair_color',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='suspect_hair_style',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='suspect_identity',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='suspect_other',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='suspect_race',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tip',
            name='location',
            field=models.TextField(),
        ),
    ]
