# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0009_auto_20160412_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='campaign',
        ),
    ]
