# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0010_remove_tip_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='suspect_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other/Unknown')], max_length=30),
        ),
    ]
