# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0016_auto_20160412_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='suspect_hair_style',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('BLACK', 'Black'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('BLOND', 'Blond'), ('RED', 'Red'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
