# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdcop_web', '0029_auto_20160413_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='suspect_eye_color',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('AMBER', 'Amber'), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('GREEN', 'Green'), ('HAZEL', 'Hazel'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='suspect_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other/Unknown')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='suspect_hair_color',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('BLACK', 'Black'), ('BROWN', 'Brown'), ('GRAY', 'Gray'), ('BLOND', 'Blond'), ('RED', 'Red'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='suspect_hair_style',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('SHORT', 'Short'), ('MEDIUM', 'Medium'), ('LONG', 'Long'), ('DREADLOCKS', 'Dreadlocks'), ('BALDING', 'Balding'), ('BALD/SHAVED', 'Bald/Shaved'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='suspect_identity',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Who did you see? (If known, enter a name or a name known by)'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='suspect_race',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('ASIAN', 'Asian'), ('BLACK/AFRICAN-AMERICAN', 'Black/African-American'), ('CAUCASIAN', 'Caucasian'), ('HISPANIC/LATINO', 'Hispanic/Latino'), ('NATIVE AMERICAN', 'Native American'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
